apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crud-ultra
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: crud-ultra
  namespaceSelector:
    matchNames:
      - crud-ultra
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
